language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database announceit_test;' -U postgres
script:
  - npm run test-live
after_success: 
  - npm run coverage
