language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - sudo -u postgres psql -c 'CREATE DATABASE announceit_test;'
  - npm run create-tables
script:
  - npm run test-live
after_success: 
  - npm run coverage
