language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -U postgres -c 'CREATE DATABASE announceit_test;'
script:
  - npm run test-live
after_success: 
  - npm run coverage
